# Basic
baseurl: ''
destination: site
title: Zijun Hui
subtitle: Doing what I like
welcome_message: Welcome to my world
description: Random thoughts and random solutions on computer science
creator: <a href="https://github.com/ZijunH/">@ZijunH</a>
url: "zijunh.github.io"

plugins: [jekyll-paginate-v2]

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Navigation buttons in the front page.
autopages:
  enabled: true
  tags: 
    enabled: false
  categories:
    title: 'Posts in category ":cat"'
    layouts:
      - autopage_category.html
    enabled: true
  collections:
    enabled: false

nav:
    - {title: Categories, description: Categoies, url: '/categories.html#blog'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

nav_new:
    # - {title: Another Button, description: A button, url: 'http://example.com'}

blog_button:
    title: Home
    description: Visit blog


# Comment
comment:
    disqus: zijunh
    # duoshuo: 
    
# Social
social:
    github: ZijunH
    mail: allenhui1220@outlook.com
    linkedin: a.com

# Google Analytics
ga:
    id: UA-132056744-1
    # host: your_host
